name: CI Cron Log

on:
  schedule:
    - cron: '*/2 * * * *' # '*/2 * * * *' for test only; original: '0 0 * * *'

jobs:
  run-cron-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print log
        run: echo "Scheduled build completed successfully"
