name: CI Matrix Build # Comment to commit and push

on:
  push:
    branches:
      - main

jobs:
  run-matrix-build:
    if: contains(github.event.head_commit.message, github.workflow)
    name: Test on Python ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python: [3.12, 3.13]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: |
          pytest test
