name: CI Runner Hello Log

on:
  push:
    branches:
      - main

jobs:
  run-hello-log:
    if: contains(github.event.head_commit.message, github.workflow)
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print hello log
        run: echo "Hello, CI with GitHub Actions!"
