name: CI Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    if: contains(github.event.head_commit.message, github.workflow)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - name: Install pytest
        run: pip install pytest

      - name: Run tests with pytest
        run: |
            pytest test     
